apiVersion: v1
kind: Pod
metadata:
  name: "discovery-platform-backend"
  labels:
    application: "discovery-platform-backend"
spec:
  securityContext:
    fsGroup: 1000

  initContainers:
  - name: mllibdriver
    image: '551806661322.dkr.ecr.eu-west-1.amazonaws.com/mllibdriver:latest'
    command: [ "/bin/sh", "-c", "cp --recursive --archive /opt/sparkbeyond/shared/tools/mllibdriver/* /mllibdriver/" ]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: mllibdriver
      mountPath: /mllibdriver

  - name: geoip
    image: '551806661322.dkr.ecr.eu-west-1.amazonaws.com/geoip:latest'
    command: [ "/bin/sh", "-c", "cp --recursive --archive /opt/sparkbeyond/local/geoip2/* /geoip2/" ]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: geoip
      mountPath: /geoip2

  containers:
  - name: main
    image: 551806661322.dkr.ecr.eu-west-1.amazonaws.com/discovery-platform/builder:R4-centos8
    imagePullPolicy: Always
    env:
    - name: "SBT_OPTS"
      value: "-Xmx20G -Xms20G"
    - name: "JAVA_OPTS"
      value: "-Xmx20G -Xms20G -XX:+CMSClassUnloadingEnabled -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:ReservedCodeCacheSize=1G"
    - name: "PIP_CONFIG_FILE"
      value: "pip.conf"
    - name: "DOCKER_HOST"
      value: "tcp://localhost:2375"
    command:
    - /tini
    - --
    - cat
    tty: true
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      privileged: true
      capabilities:
        add:
        - IPC_LOCK
        - SYS_RESOURCE
    resources:
      requests:
        memory: "22Gi"
        cpu: "200m"
      limits:
        memory: "30Gi"
        cpu: "8000m"
    volumeMounts:
    # Dependencies:
    - name: dp-efs-storage
      mountPath: /opt/sparkbeyond/shared
      readOnly: false
    - name: mllibdriver
      mountPath: /opt/sparkbeyond/shared/tools/mllibdriver
      readOnly: false
    - name: geoip
      mountPath: /opt/sparkbeyond/local/geoip2
      readOnly: false

  # Knowledge Server is required for Engine tests phase3:
  - name: knowledgeserver
    image: 551806661322.dkr.ecr.eu-west-1.amazonaws.com/knowledge-server:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
      name: knowledgeserver
    env:
    - name: "CHANGE_BRANCH"
      value: "master"
    - name: MONGO_HOST
      value: "localhost"
    - name: MONGO_PORT
      value: "27017"
    - name: KNOWLEDGE_NOAA_FTP_SERVER
      value: "http://noaa.ci.dev.sparkbeyond.ai"
    - name: KNOWLEDGE_SERVER_PORT
      value: "3000"
    - name: KNOWLEDGE_ROUTER_PORT
      value: "3100"
    resources:
      requests:
        memory: "1Gi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

  - name: ebsinit
    image: 551806661322.dkr.ecr.eu-west-1.amazonaws.com/ebsinit
    command:
      - cat
    tty: true
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
      privileged: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"

  - name: mongo
    image: nexus.sparkbeyond.ai/mongo:4.4.1-bionic
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 27017
      name: mongo
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.8.1-debug
    imagePullPolicy: IfNotPresent
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/config.json
      subPath: .dockerconfigjson

  - name: dind
    image: nexus.sparkbeyond.ai/docker:19.03.1-dind
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""

  - name: rpmbuild
    image: 551806661322.dkr.ecr.eu-west-1.amazonaws.com/base-images/rpm-build
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "1Gi"
        cpu: "2000m"
      limits:
        memory: "4Gi"
        cpu: "6000m"

  - name: jira-client
    image: 551806661322.dkr.ecr.eu-west-1.amazonaws.com/jira/ticket-generator:0.0.4
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  - name: jenkins-trigger-decision-maker
    image: 551806661322.dkr.ecr.eu-west-1.amazonaws.com/kaas/jenkins-trigger-decision-maker:main-0371ca3
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1000
    command:
      - cat
    tty: true
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1000m"

  volumes:
  # Dependencies:
  - name: dp-efs-storage
    persistentVolumeClaim:
      claimName: dp-efs-pvc
  - name: mllibdriver
    emptyDir: {}
  - name: geoip
    emptyDir: {}

  - name: docker-config
    configMap:
      name: dp-ecr-docker-config
